apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-sso-prod
resources:
  - namespace.yaml
  - secret.yaml
  - ../../base
patches:
- path: domain.json
  target:
    kind: Ingress
    name: sso-ingress
images:
  - name: scgskku/scg-sso 
    newTag: 8583ab12ee68895e3399085ecb974f739b31b01e
