apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-sso-prod

patches:
- path: domain.json
  target:
    kind: Ingress
    name: sso-ingress

resources:
  - ../../base
  - namespace.yaml
  - secret.yaml

images:
  - name: scgskku/scg-sso 
    newTag: c3e0a3004e63a6410d307cd2b5ebbecc30dacf42