apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: scg-sso-prod

patchesStrategicMerge:
  - ingress.yaml
  - deployment.yaml
  - service.yaml

resources:
  - ../../base
  - namespace.yaml
  - secret.yaml

images:
  - name: scgskku/scg-sso 
    newTag: c3e0a3004e63a6410d307cd2b5ebbecc30dacf42