apiVersion: v1
kind: Secret
metadata:
  name: scg-sso-secret
type: Opaque
data:
  KC_DB: <path:kv/data/keycloak-sso#db-vendor | base64encode>
  KC_BOOTSTRAP_ADMIN_USERNAME: <path:kv/data/keycloak-sso#kc-admin | base64encode>
  KC_BOOTSTRAP_ADMIN_PASSWORD: <path:kv/data/keycloak-sso#kc-admin-pw | base64encode>
  KC_DB_URL_HOST: <path:kv/data/keycloak-sso#db-host | base64encode>
  KC_DB_URL_PORT: <path:kv/data/keycloak-sso#db-port | base64encode>
  KC_DB_URL_DATABASE: <path:kv/data/keycloak-sso#db-database | base64encode>
  KC_DB_USERNAME: <path:kv/data/keycloak-sso#db-username | base64encode>
  KC_DB_PASSWORD: <path:kv/data/keycloak-sso#db-password | base64encode>
  KC_HOSTNAME: <path:kv/data/keycloak-sso#kc-hostname | base64encode>
  KC_PROXY: <path:kv/data/keycloak-sso#kc-proxy | base64encode>
# 04/02 update
