apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sso-ingress
  annotations:
    kubernetes.io/ingress.class: 'nginx'
    cert-manager.io/cluster-issuer: 'letsencrypt-clusterissuer'
    nginx.ingress.kubernetes.io/proxy-body-size: "200m"
    nginx.ingress.kubernetes.io/app-root: /realms/inhouse/account
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Host $host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

  
spec:
  tls:
    - hosts:
        - blabla.scg.skku.ac.kr
      secretName: gitops-tls
  rules:
    - host: blabla.scg.skku.ac.kr
      http:
        paths:
          - backend:
              service:
                name: sso-service
                port:
                  number: 80
            path: /
            pathType: Prefix
